# Generated by Django 6.0.2 on 2026-03-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pressureframe',
            name='predicted_risk_score',
            field=models.FloatField(default=0.0),
        ),
    ]
